services:
  nginx-1:
    image: nginx:latest
    #   ports:
    #     - "8081:80" # on host!
    networks:
      - nginx-net
    environment:
      MYNAME: "nginx-1"

  nginx-2:
    image: nginx:latest
    #   ports:
    #     - "8082:80"
    networks:
      - nginx-net
    environment:
      MYNAME: "nginx-2"

  nginx-3:
    image: nginx:latest
    #   ports:
    #     - "8083:80"
    networks:
      - blue-net
    environment:
      MYNAME: "nginx-3"

networks:
  nginx-net:
  blue-net:
