apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: default
  labels:
    app: it-tools
spec:
  selector:
    matchLabels:
      app: it-tools
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: it-tools
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: docker-repository.healthresearch.org:8443/it-tools:newpath  # YOUR CUSTOM IMAGE
        ports:
        - containerPort: 80
          name: it-tools
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
spec:
  selector:
    app: it-tools
  ports:
  - name: it-tools
    protocol: TCP
    port: 8080
    targetPort: it-tools
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
  labels:
    app: it-tools
spec:
  ingressClassName: nginx
  rules:
  - host: ringo.healthresearch.org
    http:
      paths:
      - path: /it-tools
        pathType: Prefix
        backend:
          service:
            name: it-tools
            port:
              number: 8080
