services:
  front-tier:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #     - ./frontend:/var/www
    #     - ./logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - front-tier
      - back-tier

  backend:
    image: nginx:latest
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf

    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
