services:
  front-tier:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #     - ./frontend:/var/www
    #     - ./logs:/var/log/nginx
    depends_on:
      - back-tier
    networks:
      - front-tier
      - back-tier

  back-tier:
    image: nginx:latest

    expose:
      - "8080"

networks:
  front-tier:
  back-tier:
